apiVersion: v1
kind: Namespace
metadata:
  name: litellm
---
apiVersion: v1
kind: Secret
metadata:
  name: google-api-key
  namespace: litellm
type: Opaque
stringData:
  GEMINI_API_KEY: "YOUR_GOOGLE_KEY_HERE"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    model_list:
      - model_name: gpt-3.5-turbo
        litellm_params:
          model: gemini/gemini-2.5-flash
          api_key: os.environ/GEMINI_API_KEY
      - model_name: gpt-4
        litellm_params:
          model: gemini/gemini-2.5-flash
          api_key: os.environ/GEMINI_API_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest
        ports:
        - containerPort: 4000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-api-key
              key: GEMINI_API_KEY
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        command: ["/bin/sh", "-c"]
        args: ["litellm --config /app/config.yaml --port 4000"]
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: litellm
spec:
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
